Repository 18F/tts-tech-portfolio, pull requests merged in 2020-07, with the labels that each got.

#471 link to new offboarding tasks spreadsheet
  .github/ISSUE_TEMPLATE/ops.md
Labels: size: days

#533 Director update to role.md
  how_we_work/roles.md
Labels: groomed: draft - final, size: days

#544 copy issue template to other repositories with Terraform
  terraform/main.tf
  terraform/repo/main.tf
  terraform/repo/vars.tf
Labels: a: demo-able, i: internal workflow

#559 TTS GitHub Repo
  how_we_work/github.md
Labels: i: internal workflow, t: hours
